# Generated by Django 5.2.4 on 2025-07-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etkinlik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Etkinlik Başlığı')),
                ('aciklama', models.TextField(verbose_name='Açıklama')),
                ('tarih', models.DateField(verbose_name='Tarih')),
                ('saat', models.TimeField(verbose_name='Saat')),
                ('yer', models.CharField(max_length=200, verbose_name='Yer')),
                ('resim', models.ImageField(blank=True, null=True, upload_to='etkinlikler/', verbose_name='Etkinlik Görseli')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
