# Generated by Django 5.2.4 on 2025-07-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duyuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Duyuru Başlığı')),
                ('aciklama', models.TextField(verbose_name='Açıklama')),
                ('tarih', models.DateField(auto_now_add=True, verbose_name='Tarih')),
                ('resim', models.ImageField(blank=True, null=True, upload_to='duyurular/', verbose_name='Duyuru Görseli')),
            ],
        ),
        migrations.CreateModel(
            name='FaydalıBilgi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Başlık')),
                ('aciklama', models.TextField(verbose_name='Açıklama')),
                ('resim', models.ImageField(blank=True, null=True, upload_to='faydali_bilgiler/', verbose_name='Görsel')),
                ('tarih', models.DateField(auto_now_add=True, verbose_name='Tarih')),
            ],
        ),
    ]
