# Generated by Django 5.2.4 on 2025-07-20 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0002_duyuru_faydalıbilgi'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FaydalıBilgi',
            new_name='FaydaliBilgi',
        ),
    ]
