# Generated by Django 5.2.4 on 2025-07-21 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0003_rename_faydalıbilgi_faydalibilgi'),
    ]

    operations = [
        migrations.CreateModel(
            name='AyasBilgi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Başlık')),
                ('aciklama', models.TextField(verbose_name='Açıklama')),
                ('resim', models.ImageField(blank=True, null=True, upload_to='ayas/', verbose_name='Görsel')),
                ('tarih', models.DateField(auto_now_add=True, verbose_name='Tarih')),
            ],
        ),
    ]
