# Generated by Django 5.2.4 on 2026-02-16 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0005_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AyasTarihi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Başlık')),
                ('aciklama', models.TextField(verbose_name='Açıklama')),
                ('tarih', models.DateField(verbose_name='Tarih')),
                ('saat', models.TimeField(verbose_name='Saat')),
                ('yer', models.CharField(max_length=200, verbose_name='Yer')),
                ('resim', models.ImageField(blank=True, null=True, upload_to='ayas_tarihi/', verbose_name='Görsel')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ayaş Tarihi',
                'verbose_name_plural': 'Ayaş Tarihi',
            },
        ),
        migrations.CreateModel(
            name='Diger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Başlık')),
                ('aciklama', models.TextField(verbose_name='Açıklama')),
                ('resim', models.ImageField(blank=True, null=True, upload_to='diger/', verbose_name='Görsel')),
                ('tarih', models.DateField(auto_now_add=True, verbose_name='Tarih')),
            ],
            options={
                'verbose_name': 'Diğer',
                'verbose_name_plural': 'Diğer',
            },
        ),
        migrations.CreateModel(
            name='GezilecekYer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Başlık')),
                ('aciklama', models.TextField(verbose_name='Açıklama')),
                ('tarih', models.DateField(auto_now_add=True, verbose_name='Tarih')),
                ('resim', models.ImageField(blank=True, null=True, upload_to='gezilecek_yerler/', verbose_name='Görsel')),
            ],
            options={
                'verbose_name': 'Gezilecek Yer',
                'verbose_name_plural': 'Gezilecek Yerler',
            },
        ),
        migrations.CreateModel(
            name='GuncelHaber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Başlık')),
                ('aciklama', models.TextField(verbose_name='Açıklama')),
                ('resim', models.ImageField(blank=True, null=True, upload_to='guncel_haberler/', verbose_name='Görsel')),
                ('tarih', models.DateField(auto_now_add=True, verbose_name='Tarih')),
            ],
            options={
                'verbose_name': 'Güncel Haber',
                'verbose_name_plural': 'Güncel Haberler',
            },
        ),
        migrations.CreateModel(
            name='KoyMahalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Başlık')),
                ('aciklama', models.TextField(verbose_name='Açıklama')),
                ('resim', models.ImageField(blank=True, null=True, upload_to='koyler_mahalleler/', verbose_name='Görsel')),
                ('tarih', models.DateField(auto_now_add=True, verbose_name='Tarih')),
            ],
            options={
                'verbose_name': 'Köy/Mahalle',
                'verbose_name_plural': 'Köyler ve Mahalleler',
            },
        ),
        migrations.DeleteModel(
            name='AyasBilgi',
        ),
        migrations.DeleteModel(
            name='Duyuru',
        ),
        migrations.DeleteModel(
            name='Etkinlik',
        ),
        migrations.DeleteModel(
            name='FaydaliBilgi',
        ),
    ]
