# Generated by Django 5.2.4 on 2026-03-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0006_ayastarihi_diger_gezilecekyer_guncelhaber_koymahalle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diger',
            name='pdf_dosya',
            field=models.FileField(blank=True, null=True, upload_to='diger/pdf/', verbose_name='PDF Dosya'),
        ),
    ]
